language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - { python: "3.6"}
    - { python: "3.7"}

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - tox

after_success:
  - codecov